name: Publish

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/install
        with:
          node_version: 20
      - name: Build
        uses: ./.github/actions/build
      - name: Publish
        shell: bash
        run: |
          npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
          npm publish
